### ISSUE TITLE
Instead of using ibkr real time data I want to use the real time data from some place else: tda-api

### ISSUE THREAD

**Issue by ppokhare** [deephaven-examples/deephaven-ib#109]
Instead of 
ticks_bid_ask = client.tables["ticks_bid_ask"]
client.request_tick_data_realtime(rc, dhib.TickDataType.BID_ASK)

I want to use tda-api level one streaming data: https://tda-api.readthedocs.io/en/latest/streaming.html

1) how can tda-api be integrated into Deephaven docker and 
2) tick_bid_ask be replace by tda-api streaming data

**Comment by chipkent** [comment]
Sorry for the delayed response.  Let me give two answers.

1. If you want to use the TDA data with IB, you can populate a table using the TDA API.  That table can then be used in queries with the IB API.  You can do this using a [DynamicTableWriter](https://deephaven.io/core/docs/reference/table-operations/create/DynamicTableWriter/) or a [TablePublisher](https://deephaven.io/core/docs/reference/table-operations/create/TablePublisher/) or Deephaven's new "function generated tables" (not yet documented).
2. If you want to trade using only TDA without IB, you will want to create some code similar to the IB plugin, but specific to TDA.  From looking at the [TDA API example](https://tda-api.readthedocs.io/en/latest/example.html), this can be done.  If you only implement the part of the API that you care about, it shouldn't be too much work.

For either path, I highly recommend getting on the Deephaven Community Slack channel.  Many users and developers there can help walk you through each of these paths.  To get on slack, go to https://deephaven.io/slack.
